/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    "whats-new",
    {
      type: "category",
      link: {
        type: "doc",
        id: "getting-started/getting-started",
      },
      label: "Getting started",
      items: [
        "getting-started/rest-api-architecture",
        "getting-started/rest-api-families",
        "getting-started/configure-clustered-environments",
        "getting-started/authentication",
        {
          type: "category",
          link: {
            type: "doc",
            id: "getting-started/improve-performance-by-working-with-partial-resources/improve-performance-by-working-with-partial-resources",
          },
          label: "Improve performance by working with partial resources",
          items: [
            "getting-started/improve-performance-by-working-with-partial-resources/field-selection-for-data-api-v2-result-fetching-endpoints",
          ],
        },
        "getting-started/handle-rest-api-exceptions",
        "getting-started/microstrategy-rest-api-explorer",
        "getting-started/playground",
        "getting-started/embedding-sdk",
      ],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "common-workflows/common-workflows",
      },
      label: "Common workflows",
      items: [
        {
          type: "category",
          label: "Analytics",
          link: {
            type: "doc",
            id: "common-workflows/analytics/analytics",
          },
          items: [
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/object-discovery/object-discovery",
              },
              label: "Object discovery",
              items: [
                "common-workflows/analytics/object-discovery/folder-browsing",
                "common-workflows/analytics/object-discovery/search-for-objects",
                "common-workflows/analytics/object-discovery/data-lineage-analysis-via-rest-apis",
              ],
            },
            {
              type: "category",
              label: "Project management",
              items: [
                "common-workflows/analytics/project-management/manage-project-load-settings-on-server-startup",
                "common-workflows/analytics/project-management/manage-project-settings",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/project-management/project-advanced-properties-management/project-advanced-properties-management",
                  },
                  label: "Manage project advanced properties",
                  items: [
                    "common-workflows/analytics/project-management/project-advanced-properties-management/get-project-applicable-advanced-properties",
                    "common-workflows/analytics/project-management/project-advanced-properties-management/get-project-with-advanced-properties",
                    "common-workflows/analytics/project-management/project-advanced-properties-management/update-project-advanced-property",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Manage reports",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/manage-reports/manage-report-objects/manage-report-objects",
                  },
                  label: "Manage report objects",
                  items: [
                    "common-workflows/analytics/manage-reports/manage-report-objects/retrieve-a-reports-definition",
                    "common-workflows/analytics/manage-reports/manage-report-objects/create-a-new-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/update-the-definition-of-an-existing-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/retrieve-a-derived-elements-definition-in-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/create-a-derived-element-in-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/delete-a-derived-element-in-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/execute-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/put-a-derived-element-in-report",
                    "common-workflows/analytics/manage-reports/manage-report-objects/retrieve-applicable-properties-of-a-report",
                  ],
                },
                "common-workflows/analytics/manage-reports/manage-page-by-information",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/manage-reports/manage-transaction-report-objects/manage-transaction-report-objects",
                  },
                  label: "Manage transaction report objects",
                  items: [
                    "common-workflows/analytics/manage-reports/manage-transaction-report-objects/retrieve-transaction-report-definition",
                    "common-workflows/analytics/manage-reports/manage-transaction-report-objects/create-a-transaction-report",
                    "common-workflows/analytics/manage-reports/manage-transaction-report-objects/update-transaction-report-definition",
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/manage-incremental-refresh-report",
                  },
                  label: "Manage incremental refresh report (IRRs)",
                  items: [
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/retrieve-an-irr-definition",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/create-an-irr",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/update-an-irr-definition",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/retrieve-an-irr-definition-with-advanced-properties",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/create-an-irr-with-advanced-properties",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/update-irr-advanced-properties",
                    "common-workflows/analytics/manage-reports/manage-incremental-refresh-report/retrieve-applicable-properties-of-an-incremental-refresh-report",
                  ],
                },
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/manage-documents/manage-documents",
              },
              label: "Manage documents",
              items: [
                "common-workflows/analytics/manage-documents/get-document-list/get-document-list",
                "common-workflows/analytics/manage-documents/retrieve-document/retrieve-the-hierarchy-of-a-document",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/manage-dossiers/manage-dossiers",
              },
              label: "Manage dashboards",
              items: ["common-workflows/analytics/manage-dossiers/create-instance/create-instance"],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/manage-datasets/manage-datasets",
              },
              label: "Manage datasets",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/manage-datasets/manage-cube-objects/manage-cube-objects",
                  },
                  label: "Manage cube objects",
                  items: [
                    "common-workflows/analytics/manage-datasets/manage-cube-objects/retrieve-a-cube-definition",
                    "common-workflows/analytics/manage-datasets/manage-cube-objects/create-a-cube-object",
                    "common-workflows/analytics/manage-datasets/manage-cube-objects/update-a-cube-definition",
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/manage-datasets/make-external-data-available/make-external-data-available",
                  },
                  label: "Make external data available using the Push Data API",
                  items: [
                    "common-workflows/analytics/manage-datasets/make-external-data-available/create-a-dataset-with-one-request/workflow-create-and-modify-a-dataset-with-one-request",
                    {
                      type: "category",
                      link: {
                        type: "doc",
                        id: "common-workflows/analytics/manage-datasets/make-external-data-available/create-a-dataset-incrementally-with-multiple-requests/create-a-dataset-incrementally-with-multiple-requests",
                      },
                      label: "Create a dataset incrementally with multiple requests",
                      items: [
                        "common-workflows/analytics/manage-datasets/make-external-data-available/create-a-dataset-incrementally-with-multiple-requests/benefits",
                        "common-workflows/analytics/manage-datasets/make-external-data-available/create-a-dataset-incrementally-with-multiple-requests/logic-for-creating-a-dataset-incrementally",
                        "common-workflows/analytics/manage-datasets/make-external-data-available/create-a-dataset-incrementally-with-multiple-requests/workflow-create-a-dataset-incrementally-with-multiple-requests",
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/retrieve-data-from-the-intelligence-server/retrieve-data-from-the-intelligence-server",
              },
              label: "Retrieve data from the Intelligence Server using the JSON Data API",
              items: [
                "common-workflows/analytics/retrieve-data-from-the-intelligence-server/workflow-retrieve-data-from-the-intelligence-server",
                "common-workflows/analytics/retrieve-data-from-the-intelligence-server/supported-features-and-considerations",
                "common-workflows/analytics/retrieve-data-from-the-intelligence-server/asynchronous-execution-of-reports-and-cubes",
              ],
            },
            "common-workflows/analytics/sort-data",
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/filter-data/filter-data",
              },
              label: "Filter data",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances",
                  },
                  label: "Filter report and cube instances",
                  items: [
                    {
                      type: "category",
                      link: {
                        type: "doc",
                        id: "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/filter-report-and-cube-instances-using-view-filters",
                      },
                      label: "Filter report and cube instances using view filters",
                      items: [
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/general-guidelines",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/supported-operators",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/supported-constant-data-types",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/code-sample",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-view-filters/error-messages",
                      ],
                    },
                    {
                      type: "category",
                      link: {
                        type: "doc",
                        id: "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-metric-limits/filter-report-and-cube-instances-using-metric-limits",
                      },
                      label: "Filter report and cube instances using metric limits",
                      items: [
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-metric-limits/supported-operators",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-metric-limits/code-sample",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-metric-limits/error-messages",
                      ],
                    },
                    {
                      type: "category",
                      link: {
                        type: "doc",
                        id: "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-requested-objects/filter-report-and-cube-instances-using-requested-objects",
                      },
                      label: "Filter report and cube instances using requestedObjects",
                      items: [
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-requested-objects/general-guidelines",
                        "common-workflows/analytics/filter-data/filter-report-and-cube-instances/filter-report-and-cube-instances-using-requested-objects/code-sample",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/filter-data/filter-dossier-instances/filter-dossier-instances",
                  },
                  label: "Filter dashboard instances",
                  items: [
                    "common-workflows/analytics/filter-data/filter-dossier-instances/apply-filters-to-a-dossier",
                  ],
                },
                "common-workflows/analytics/filter-data/retrieve-filters-applied-to-dossier-chapters",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/filter-data/retrieve-filters-applied-to-a-visualization/retrieve-filters-applied-to-a-visualization",
                  },
                  label: "Retrieve filters applied to a visualization",
                  items: [
                    "common-workflows/analytics/filter-data/retrieve-filters-applied-to-a-visualization/return-metric-based-view-filters",
                    "common-workflows/analytics/filter-data/retrieve-filters-applied-to-a-visualization/return-attribute-based-view-filters",
                    "common-workflows/analytics/filter-data/retrieve-filters-applied-to-a-visualization/return-template-limit-criteria",
                    "common-workflows/analytics/filter-data/retrieve-filters-applied-to-a-visualization/return-metric-limit-criteria",
                  ],
                },
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/use-prompts-objects/use-prompts-objects",
              },
              label: "Use prompts objects",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/use-prompts-objects/get-prompt-information/get-prompt-information",
                  },
                  label: "Get prompt information",
                  items: [
                    "common-workflows/analytics/use-prompts-objects/get-prompt-information/workflow-get-prompt-information",
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/analytics/use-prompts-objects/prompt-types/prompt-types",
                  },
                  label: "Prompt types",
                  items: [
                    "common-workflows/analytics/use-prompts-objects/prompt-types/attribute-element-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/attribute-qualification-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/object-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/value-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/metric-expression-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/hierarchy-qualification-prompts",
                    "common-workflows/analytics/use-prompts-objects/prompt-types/level-prompts",
                  ],
                },
                "common-workflows/analytics/use-prompts-objects/answer-prompts",
                "common-workflows/analytics/use-prompts-objects/prompt-execution-errors",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/manage-selectors/manage-selectors",
              },
              label: "Manage selectors",
              items: [
                "common-workflows/analytics/manage-selectors/retrieve-a-selectors-definition",
                "common-workflows/analytics/manage-selectors/set-selector-type",
              ],
            },
            "common-workflows/analytics/export-to-pdf",
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/retrieve-sql-statements-and-query-details/retrieve-sql-statements-and-query-details",
              },
              label: "Retrieve SQL statements and query details",
              items: [
                "common-workflows/analytics/retrieve-sql-statements-and-query-details/retrieve-report-or-card-sql",
                "common-workflows/analytics/retrieve-sql-statements-and-query-details/retrieve-dataset-sql",
                "common-workflows/analytics/retrieve-sql-statements-and-query-details/retrieve-visualization-query-details",
                "common-workflows/analytics/retrieve-sql-statements-and-query-details/retrieve-grid-or-graph-query-details",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/analytics/manage-insights/manage-kpi-and-insights",
              },
              label: "Manage insights",
              items: [
                "common-workflows/analytics/manage-insights/create-kpi",
                "common-workflows/analytics/manage-insights/get-kpi",
                "common-workflows/analytics/manage-insights/modify-kpi",
                "common-workflows/analytics/manage-insights/delete-kpi",
                "common-workflows/analytics/manage-insights/retrieve-an-insight",
                "common-workflows/analytics/manage-insights/retrieve-all-insights",
                "common-workflows/analytics/manage-insights/retrieve-insight-preferences",
                "common-workflows/analytics/manage-insights/update-insight-preferences",
                "common-workflows/analytics/manage-insights/update-insight-status",
              ],
            },
            {
              type: "category",
              label: "Bot APIs",
              items: [
                "common-workflows/analytics/use-bot-api/use-bot-api",
                "common-workflows/analytics/use-bot-api/get-bot-configuration",
                "common-workflows/analytics/use-bot-api/get-bot-question-list",
                "common-workflows/analytics/use-bot-api/create-a-bot-instance",
                "common-workflows/analytics/use-bot-api/ask-bot-instance-suggested-question",
                "common-workflows/analytics/use-bot-api/ask-bot-instance-question",
                "common-workflows/analytics/use-bot-api/get-a-bot-question",
                "common-workflows/analytics/use-bot-api/delete-a-bot-instance",
              ],
            },
            {
              type: "category",
              label: "Question with Bot Routing APIs",
              items: [
                "common-workflows/analytics/question-with-bot-routing-api/question-api",
                "common-workflows/analytics/question-with-bot-routing-api/ask-question-to-bots-in-the-application",
                "common-workflows/analytics/question-with-bot-routing-api/get-question-from-bots-in-the-application",
                "common-workflows/analytics/question-with-bot-routing-api/get-image-of-answer",
                "common-workflows/analytics/question-with-bot-routing-api/ask-suggested-question-to-bots-in-the-application",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Modeling",
          link: {
            type: "doc",
            id: "common-workflows/modeling/modeling",
          },
          items: [
            {
              type: "category",
              label: "Common object management",
              items: [
                "common-workflows/modeling/common-object-management/manage-object-acl",
                "common-workflows/modeling/common-object-management/change-ownership",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/modeling/common-object-management/manage-object-translations/manage-object-translations",
                  },
                  label: "Manage object's translations",
                  items: [
                    "common-workflows/modeling/common-object-management/manage-object-translations/retrieve-object-translations",
                    "common-workflows/modeling/common-object-management/manage-object-translations/remove-add-object-translations",
                    "common-workflows/modeling/common-object-management/manage-object-translations/update-object-translations",
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/modeling/common-object-management/manage-the-schema/manage-the-schema",
                  },
                  label: "Manage the schema",
                  items: [
                    "common-workflows/modeling/common-object-management/manage-the-schema/retrieve-the-schema-lock",
                    "common-workflows/modeling/common-object-management/manage-the-schema/lock-the-schema",
                    "common-workflows/modeling/common-object-management/manage-the-schema/unlock-the-schema",
                    "common-workflows/modeling/common-object-management/manage-the-schema/reload-the-schema-synchronously",
                    "common-workflows/modeling/common-object-management/manage-the-schema/reload-the-schema-asynchronously",
                  ],
                },
              ],
            },
            "common-workflows/modeling/changesets",
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-attribute-objects/manage-attribute-objects",
              },
              label: "Manage attribute objects",
              items: [
                "common-workflows/modeling/manage-attribute-objects/retrieve-an-attributes-definition",
                "common-workflows/modeling/manage-attribute-objects/retrieve-an-attributes-definition-within-a-changeset",
                "common-workflows/modeling/manage-attribute-objects/create-an-attribute-object",
                "common-workflows/modeling/manage-attribute-objects/update-an-attributes-definition",
                "common-workflows/modeling/manage-attribute-objects/get-attribute-applicable-advanced-properties",
                "common-workflows/modeling/manage-attribute-objects/get-attribute-with-advanced-properties",
                "common-workflows/modeling/manage-attribute-objects/update-attribute-advanced-property",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-attribute-relationships/manage-attribute-relationships",
              },
              label: "Manage attribute relationships",
              items: [
                "common-workflows/modeling/manage-attribute-relationships/retrieve-an-attributes-relationships",
                "common-workflows/modeling/manage-attribute-relationships/retrieve-an-attributes-relationships-within-a-changeset",
                "common-workflows/modeling/manage-attribute-relationships/update-an-attributes-relationships",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-base-formula-objects/manage-base-formula-objects",
              },
              label: "Manage base formula objects",
              items: [
                "common-workflows/modeling/manage-base-formula-objects/retrieve-a-base-formulas-definition",
                "common-workflows/modeling/manage-base-formula-objects/retrieve-a-base-formulas-definition-within-a-changeset",
                "common-workflows/modeling/manage-base-formula-objects/create-a-base-formulas-definition-within-a-changeset",
                "common-workflows/modeling/manage-base-formula-objects/update-a-base-formulas-definition-within-a-changeset",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-calendar-objects/manage-calendar-objects",
              },
              label: "Manage calendar objects",
              items: [
                "common-workflows/modeling/manage-calendar-objects/retrieve-a-list-of-calendars-definitions",
                "common-workflows/modeling/manage-calendar-objects/retrieve-a-calendar-definition",
                "common-workflows/modeling/manage-calendar-objects/create-a-calendar-object",
                "common-workflows/modeling/manage-calendar-objects/update-a-calendar-object",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-consolidation-objects/manage-consolidation-objects",
              },
              label: "Manage consolidation objects",
              items: [
                "common-workflows/modeling/manage-consolidation-objects/retrieve-a-consolidations-definition",
                "common-workflows/modeling/manage-consolidation-objects/create-a-consolidation-object",
                "common-workflows/modeling/manage-consolidation-objects/update-a-consolidation-object",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-custom-group-objects/manage-custom-group-objects",
              },
              label: "Manage custom group objects",
              items: [
                "common-workflows/modeling/manage-custom-group-objects/retrieve-a-custom-groups-definition",
                "common-workflows/modeling/manage-custom-group-objects/retrieve-a-custom-groups-definition-within-a-changeset",
                "common-workflows/modeling/manage-custom-group-objects/create-a-custom-group-object",
                "common-workflows/modeling/manage-custom-group-objects/create-a-custom-group-object-with-filter-elements-using-custom-expressions",
                "common-workflows/modeling/manage-custom-group-objects/update-a-custom-groups-definition",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-datamart-objects/manage-datamart-objects",
              },
              label: "Manage datamart objects",
              items: [
                "common-workflows/modeling/manage-datamart-objects/retrieve-a-datamart-definition",
                "common-workflows/modeling/manage-datamart-objects/create-a-datamart-from-a-source-report",
                "common-workflows/modeling/manage-datamart-objects/create-a-datamart-from-scratch",
                "common-workflows/modeling/manage-datamart-objects/update-a-datamart-definition",
                "common-workflows/modeling/manage-datamart-objects/retrieve-applicable-properties-of-a-datamart",
                "common-workflows/modeling/manage-datamart-objects/execute-a-datamart",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-derived-element-objects/manage-derived-element-objects",
              },
              label: "Manage derived element objects",
              items: [
                "common-workflows/modeling/manage-derived-element-objects/retrieve-a-derived-elements-definition",
                "common-workflows/modeling/manage-derived-element-objects/create-a-derived-element",
                "common-workflows/modeling/manage-derived-element-objects/replace-an-existing-element",
                "common-workflows/modeling/manage-derived-element-objects/format-samples",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-dossier-themes/manage-dossier-themes",
              },
              label: "Manage dashboard themes",
              items: [
                "common-workflows/modeling/manage-dossier-themes/dossier-theme-instance-creation",
                "common-workflows/modeling/manage-dossier-themes/save-dossier-themes",
                "common-workflows/modeling/manage-dossier-themes/get-dossier-theme-json",
                "common-workflows/modeling/manage-dossier-themes/apply-dossier-theme",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-drill-maps/manage-drill-maps",
              },
              label: "Manage drill maps",
              items: [
                "common-workflows/modeling/manage-drill-maps/retrieve-a-drill-map-definition",
                "common-workflows/modeling/manage-drill-maps/create-a-drill-map",
                "common-workflows/modeling/manage-drill-maps/update-a-drill-map",
                "common-workflows/modeling/manage-drill-maps/retrieve-a-list-of-objects",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-fact-objects/manage-fact-objects",
              },
              label: "Manage fact objects",
              items: [
                "common-workflows/modeling/manage-fact-objects/retrieve-a-facts-definition",
                "common-workflows/modeling/manage-fact-objects/retrieve-a-facts-definition-within-a-changeset",
                "common-workflows/modeling/manage-fact-objects/create-a-fact-object",
                "common-workflows/modeling/manage-fact-objects/update-a-fact-object",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-filter-objects/manage-filter-objects",
              },
              label: "Manage filter objects",
              items: [
                "common-workflows/modeling/manage-filter-objects/retrieve-a-filters-definition",
                "common-workflows/modeling/manage-filter-objects/retrieve-a-filters-definition-within-a-changeset",
                "common-workflows/modeling/manage-filter-objects/create-a-filter-object",
                "common-workflows/modeling/manage-filter-objects/create-a-filter-object-with-a-custom-expression",
                "common-workflows/modeling/manage-filter-objects/update-a-filters-definition",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-metric-objects/manage-metric-objects",
              },
              label: "Manage metric objects",
              items: [
                "common-workflows/modeling/manage-metric-objects/retrieve-a-metrics-definition",
                "common-workflows/modeling/manage-metric-objects/retrieve-a-metrics-definition-within-a-changeset",
                "common-workflows/modeling/manage-metric-objects/create-a-metric-within-a-changeset",
                "common-workflows/modeling/manage-metric-objects/update-a-metrics-definition-within-a-changeset",
                "common-workflows/modeling/manage-metric-objects/retrieve-a-metrics-applicable-properties",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-prompt-objects/manage-prompt-objects",
              },
              label: "Manage prompt objects",
              items: [
                "common-workflows/modeling/manage-prompt-objects/retrieve-a-prompts-definition",
                "common-workflows/modeling/manage-prompt-objects/create-a-prompt-within-a-changeset",
                "common-workflows/modeling/manage-prompt-objects/update-a-prompts-definition-within-a-changeset",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/modeling/manage-prompt-objects/prompt-types/prompt-types",
                  },
                  label: "Prompt types for managing prompt objects",
                  items: [
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/attribute-element-prompts",
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/attribute-qualification-prompts",
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/hierarchy-qualification-prompts",
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/metric-expression-prompts",
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/object-prompts",
                    "common-workflows/modeling/manage-prompt-objects/prompt-types/value-prompts",
                  ],
                },
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-security-filter-objects/manage-security-filter-objects",
              },
              label: "Manage security filter objects",
              items: [
                "common-workflows/modeling/manage-security-filter-objects/retrieve-a-security-filter-definition",
                "common-workflows/modeling/manage-security-filter-objects/create-a-security-filter-object",
                "common-workflows/modeling/manage-security-filter-objects/update-a-security-filter-definition",
                "common-workflows/modeling/manage-security-filter-objects/create-a-security-filter-object-using-a-custom-expression",
                "common-workflows/modeling/manage-security-filter-objects/retrieve-a-security-filters-member",
                "common-workflows/modeling/manage-security-filter-objects/modify-a-security-filters-member",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-subtotal-objects/manage-subtotal-objects",
              },
              label: "Manage subtotal objects",
              items: [
                "common-workflows/modeling/manage-subtotal-objects/retrieve-a-subtotals-definition",
                "common-workflows/modeling/manage-subtotal-objects/retrieve-a-subtotals-definition-within-a-changeset",
                "common-workflows/modeling/manage-subtotal-objects/create-a-subtotal-within-a-changeset",
                "common-workflows/modeling/manage-subtotal-objects/update-a-subtotal-within-a-changeset",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-table-objects/manage-table-objects",
              },
              label: "Manage table objects",
              items: [
                "common-workflows/modeling/manage-table-objects/retrieve-a-list-of-all-available-table-definitions",
                "common-workflows/modeling/manage-table-objects/retrieve-a-tables-definition",
                "common-workflows/modeling/manage-table-objects/create-a-new-table-object",
                "common-workflows/modeling/manage-table-objects/update-a-tables-definition",
                "common-workflows/modeling/manage-table-objects/retrieve-a-prompt-of-an-sap-hana-table",
                "common-workflows/modeling/manage-table-objects/update-a-prompt-of-an-sap-hana-table",
                "common-workflows/modeling/manage-table-objects/update-sap-hana-parameters",
                "common-workflows/modeling/manage-table-objects/retrieve-a-partition-mapping-tables-definition",
                "common-workflows/modeling/manage-table-objects/create-a-new-partition-mapping-table-object",
                "common-workflows/modeling/manage-table-objects/update-a-partition-mapping-tables-definition",
                "common-workflows/modeling/manage-table-objects/update-a-tables-physical-table-structure",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-transformation-objects/manage-transformation-objects",
              },
              label: "Manage transformation objects",
              items: [
                "common-workflows/modeling/manage-transformation-objects/retrieve-a-transformations-definition",
                "common-workflows/modeling/manage-transformation-objects/create-a-transformation-object",
                "common-workflows/modeling/manage-transformation-objects/update-a-transformations-definition",
              ],
            },

            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/modeling/manage-user-hierarchy-objects/manage-user-hierarchy-objects",
              },
              label: "Manage user hierarchy objects",
              items: [
                "common-workflows/modeling/manage-user-hierarchy-objects/retrieve-a-user-hierarchys-definition",
                "common-workflows/modeling/manage-user-hierarchy-objects/create-a-user-hierarchy",
                "common-workflows/modeling/manage-user-hierarchy-objects/update-a-user-hierarchys-definition",
                "common-workflows/modeling/manage-user-hierarchy-objects/retrieve-a-list-of-available-user-hierarchies",
                "common-workflows/modeling/manage-user-hierarchy-objects/user-hierarchy-import-parameters",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Administration",
          link: {
            type: "doc",
            id: "common-workflows/administration/administration",
          },
          items: [
            {
              type: "category",
              label: "Server management",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/server-management/server-level-privileges/server-level-privileges",
                  },
                  label: "Server-level privileges",
                  items: [
                    "common-workflows/administration/server-management/server-level-privileges/manage-server-level-privileges",
                    "common-workflows/administration/server-management/server-level-privileges/watch-kpi-insight-service-privileges",
                  ],
                },
                "common-workflows/administration/server-management/manage-server-settings",
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/server-management/manage-fences/manage-fences",
                  },
                  label: "Manage fences",
                  items: [
                    "common-workflows/administration/server-management/manage-fences/retrieve-list-of-fences",
                    "common-workflows/administration/server-management/manage-fences/retrieve-specific-fence",
                    "common-workflows/administration/server-management/manage-fences/create-fence",
                    "common-workflows/administration/server-management/manage-fences/update-specific-fence",
                    "common-workflows/administration/server-management/manage-fences/delete-specific-fence",
                  ],
                },
                "common-workflows/administration/server-management/manage-languages",
                "common-workflows/administration/server-management/manage-quick-search-indices",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/user-management/manage-user-and-user-groups",
              },
              label: "User management",
              items: [
                "common-workflows/administration/user-management/create-and-update-user-groups",
                "common-workflows/administration/user-management/create-new-users",
                "common-workflows/administration/user-management/manage-users",
                "common-workflows/administration/user-management/create-security-roles",
              ],
            },
            {
              type: "category",
              label: "Monitors",
              items: [
                "common-workflows/administration/monitors/manage-an-intelligence-server-cluster",
                {
                  type: "doc",
                  id: "common-workflows/administration/monitors/manage-caches",
                  label: "Purge object and element caches",
                },
                "common-workflows/administration/monitors/monitor-and-manage-cube-caches",
                "common-workflows/administration/monitors/project-administration",
              ],
            },
            {
              type: "category",
              label: "History list",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/manage-history-lists/manage-history-lists",
                  },
                  label: "Manage History Lists",
                  items: [
                    "common-workflows/administration/manage-history-lists/get-history-list/get-history-list",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Distribution services",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/distribution-services/manage-subscriptions/manage-subscriptions",
                  },
                  label: "Manage subscriptions",
                  items: [
                    {
                      type: "category",
                      link: {
                        type: "doc",
                        id: "common-workflows/administration/distribution-services/manage-subscriptions/create-and-get-a-subscription",
                      },
                      label: "Create and get a subscription",
                      items: [
                        "common-workflows/administration/distribution-services/manage-subscriptions/mobile-subscriptions",
                      ],
                    },
                    "common-workflows/administration/distribution-services/manage-subscriptions/create-subscription-for-multi-content",
                    "common-workflows/administration/distribution-services/manage-subscriptions/create-subscription-with-prompted-content",
                  ],
                },
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/datasource-management/datasource-management",
              },
              label: "Datasource management",
              items: [
                "common-workflows/administration/datasource-management/create-a-datasource",
                "common-workflows/administration/datasource-management/update-a-datasource",
                "common-workflows/administration/datasource-management/add-and-remove-datasource-from-project",
                "common-workflows/administration/datasource-management/update-job-priorities-for-datasource",
                "common-workflows/administration/datasource-management/delete-a-datasource",
                "common-workflows/administration/datasource-management/get-datasource-applicable-advanced-properties",
                "common-workflows/administration/datasource-management/get-datasource-with-advanced-properties",
                "common-workflows/administration/datasource-management/update-datasource-advanced-property",
                "common-workflows/administration/datasource-management/convert-connection-string-from-dsn-to-dsnless-for-a-datasource",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-gateways/manage-gateways",
              },
              label: "Manage Gateways",
              items: [
                "common-workflows/administration/manage-gateways/retrieve-gateways",
                "common-workflows/administration/manage-gateways/retrieve-a-gateway-definition",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-licensing/manage-licensing",
              },
              label: "Manage Licensing",
              items: [
                "common-workflows/administration/manage-licensing/license-manipulation",
                "common-workflows/administration/manage-licensing/license-audit-compliance",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-drivers/manage-drivers",
              },
              label: "Manage Drivers",
              items: [
                "common-workflows/administration/manage-drivers/retrieve-drivers",
                "common-workflows/administration/manage-drivers/retrieve-a-driver-definition",
                "common-workflows/administration/manage-drivers/update-a-driver-definition",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-runtime-objects/manage-runtimes",
              },
              label: "Manage runtimes",
              items: [
                "common-workflows/administration/manage-runtime-objects/retrieve-all-runtimes",
                "common-workflows/administration/manage-runtime-objects/retrieve-a-runtime-definition",
                "common-workflows/administration/manage-runtime-objects/create-a-runtime",
                "common-workflows/administration/manage-runtime-objects/update-a-runtime",
                "common-workflows/administration/manage-runtime-objects/delete-a-runtime",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-application-objects/manage-application-objects",
              },
              label: "Manage application objects",
              items: [
                "common-workflows/administration/manage-application-objects/manage-application-general-settings",
                "common-workflows/administration/manage-application-objects/manage-application-customized-emails",
                "common-workflows/administration/manage-application-objects/manage-application-themes",
              ],
            },
            {
              type: "category",
              link: {
                type: "doc",
                id: "common-workflows/administration/manage-content-group-objects/manage-content-group-objects",
              },
              label: "Manage content group objects",
              items: [
                "common-workflows/administration/manage-content-group-objects/retrieve-a-content-group",
                "common-workflows/administration/manage-content-group-objects/retrieve-all-content-groups",
                "common-workflows/administration/manage-content-group-objects/create-a-content-group",
                "common-workflows/administration/manage-content-group-objects/update-a-content-group",
                "common-workflows/administration/manage-content-group-objects/retrieve-contents-of-an-existing-content-group",
                "common-workflows/administration/manage-content-group-objects/update-contents-of-an-existing-content-group",
              ],
            },
            {
              type: "category",
              label: "Migrations",
              items: [
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/migrations/migrations-in-workstation/migrations-in-workstation",
                  },
                  label: "Migrations in Workstation",
                  items: [
                    "common-workflows/administration/migrations/migrations-in-workstation/object-migration-between-environments",
                    "common-workflows/administration/migrations/migrations-in-workstation/project-merge-between-environments",
                    "common-workflows/administration/migrations/migrations-in-workstation/validate-migrations",
                    "common-workflows/administration/migrations/migrations-in-workstation/object-migration-groups-between-environments",
                    "common-workflows/administration/migrations/migrations-in-workstation/upload-and-download-migration-packages",
                    "common-workflows/administration/migrations/migrations-in-workstation/edit-migrations-and-migration-groups",
                  ],
                },
                {
                  type: "category",
                  link: {
                    type: "doc",
                    id: "common-workflows/administration/migrations/create-and-import-migration-packages/create-and-import-migration-packages",
                  },
                  label: "Create and import migration packages",
                  items: [
                    "common-workflows/administration/migrations/create-and-import-migration-packages/create-a-migration-package",
                    "common-workflows/administration/migrations/create-and-import-migration-packages/import-a-migration-package",
                    "common-workflows/administration/migrations/create-and-import-migration-packages/view-newly-created-package",
                    "common-workflows/administration/migrations/create-and-import-migration-packages/view-uploaded-package",
                    "common-workflows/administration/migrations/create-and-import-migration-packages/manage-content-group-packages",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "microstrategy-rest-api-samples/microstrategy-rest-api-samples",
      },
      label: "MicroStrategy REST API samples",
      items: [
        "microstrategy-rest-api-samples/create-reports-on-the-fly",
        "microstrategy-rest-api-samples/react-user-manage-sample",
      ],
    },
  ],
};

// const sidebars = {
//   myAutogeneratedSidebar: [
//     {
//       type: "autogenerated",
//       dirName: ".", // '.' means the current docs folder
//     },
//   ],
// };

module.exports = sidebars;
